name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || ((contains(github.ref, '[test]') || contains(github.ref, '[TEST]'))
    strategy:
      matrix:
        python-version: [3.6, 3.9, 3.12]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -e .
      - name: Run tests
        run: python -m unittest discover -s Effortless/tests
